services:
  - mysql
before_install:
  - COMMIT=`git log -n 1 2>/dev/null | grep "commit " | cut -c7-`
  - BRANCH=`git branch -r --contains $COMMIT 2>/dev/null | cut -c10- | head -1`
  - git submodule update --init --recursive
  - git clone git://github.com/novius-os/ci.git
  - cd ci
  - echo $BRANCH
  - git checkout $BRANCH
  - cd ..
  - sudo apt-get install -y --force-yes apache2 php5 libapache2-mod-php5 php5-mysql php-pear
  - sudo a2enmod rewrite
  - cat ci/virtualhost | sed -e "s,PATH,`pwd`/public,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 reload
  - sudo sh -c 'echo "127.0.0.1 novius-os" >> /etc/hosts'
  - chmod a+w local/config
  - chmod a+w local/data/
  - chmod a+w local/metadata
  - chmod a+w public/
  - ln -s ../../novius-os/htdocs public/htdocs/novius-os
  - chmod a+w public/htdocs/apps
  - ln -s ../../novius-os/static public/static/novius-os
  - chmod a+w public/static/apps
  - chmod a+w logs/fuel
  - chmod a+w local/cache
  - chmod a+w local/data/media
  - chmod a+w local/cache/media
  - chmod a+w local/data/config
  - chmod a+w public/cache
  - chmod a+w public/cache/media
  - chmod a+w public/media
  - sudo sh -c 'pear channel-discover pear.phpunit.de'
  - sudo sh -c 'pear install --alldeps pear/PHP_CodeSniffer'
before_script:
  - mysql -e 'CREATE DATABASE novius_os DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - phpcs -s -n --standard=ci/phpcs/ruleset.xml --extensions=php --report-summary ./
  - "DISPLAY=:99.0 ./ci/casperjs/bin/casperjs test ./ci/tests/casperjs/demo.js --direct --log-level=info --fail-fast --includes=./ci/tests/casperjs/pre.js"
  - "DISPLAY=:99.0 ./ci/casperjs/bin/casperjs test ./ci/tests/casperjs/install.js --direct --log-level=info --fail-fast --includes=./ci/tests/casperjs/pre.js --base_url='http://novius-os/'"
  - "DISPLAY=:99.0 ./ci/casperjs/bin/casperjs test ./ci/tests/casperjs/appmanager.js --direct --log-level=info --fail-fast --includes=./ci/tests/casperjs/pre.js --base_url='http://novius-os/'"
  - "DISPLAY=:99.0 ./ci/casperjs/bin/casperjs test ./ci/tests/casperjs/page.js --direct --log-level=info --fail-fast --includes=./ci/tests/casperjs/pre.js --base_url='http://novius-os/'"

